const cmsData = {
  title: "Cadastre-se Gratuitamente",
  fields: [
    {
      label: "Nome pessoal",
      id: "personalName",
      type: "text",
      required: true,
      msmError: "Por favor preencha seu nome",
      size: "full",
      horizontaLine: false,
    },
    {
      label: "E-mail",
      id: "email",
      type: "email",
      required: true,
      msmError: "Por favor preencha seu e-mail",
      size: "full",
      horizontaLine: false,
    },
    {
      label: "Senha",
      id: "password",
      type: "password",
      required: true,
      msmError: "Por favor digite uma senha",
      size: "half-first",
      horizontaLine: false,
    },
    {
      label: "Confirme sua senha",
      id: "confirmPassword",
      type: "password",
      required: true,
      msmError: "A confirmação da senha deve ser igual a senha",
      size: "half-last",
      horizontaLine: false,
    },
    {
      label: "Nome da empresa",
      id: "companyName",
      type: "text",
      required: true,
      msmError: "Por favor preencha o nome da sua empresa",
      size: "full",
      horizontaLine: true,
    },
    {
      label: "Site / Facebook",
      id: "companySite",
      type: "text",
      required: false,
      msmError: "",
      size: "full",
      horizontaLine: false,
    },
  ],
  labelSubmit: "Finalizar Cadastro",
}
export default cmsData
